#!/bin/bash
# Auto-starts the local ssh forwarding, and then opens a GUI for each of the test users.

CONFIG=$HOME/.parallel_calabash.autostart
PORT=6900

USERS=$(ruby -le 'puts eval(File.read("'$CONFIG'"))[:USERS].join(",")')
PASSWORD=$(ruby -le 'puts eval(File.read("'$CONFIG'"))[:PASSWORD]')

( ssh -N -L $PORT:localhost:5900 ${USERS%%,*}@localhost & ) &

until lsof -i -P|grep -i listen | grep $PORT ; do sleep 1; done

for USER in $(echo $USERS | tr ',' ' ') ; do
    ${0%/*}/opengui.applescript vnc://$USER:$PASSWORD@localhost:$PORT
done
